import type { ObjectValues } from "@bot-types";
import { DATABASE_MODELS, DatabaseModels } from "./DatabaseModels";

export const ACTION_CODES = {
    ACTION_REGISTER_CHAMPIONSHIP: "ACTION_REGISTER_CHAMPIONSHIP",
    ACTION_SEARCH_OPPONENT_CHAMPIONSHIP: "ACTION_SEARCH_OPPONENT_CHAMPIONSHIP",
    ACTION_SHOW_WEAPON_CATEGORY_SELECTION: "ACTION_SHOW_WEAPON_CATEGORY_SELECTION",
    ACTION_SHOW_WEAPONS_SELECTION: "ACTION_SHOW_WEAPONS_SELECTION",
    ACTION_UPDATE_WEAPONS_SELECTION: "ACTION_UPDATE_WEAPONS_SELECTION",
    ACTION_VALIDATE_WEAPONS_SELECTION: "ACTION_VALIDATE_WEAPONS_SELECTION"
} as const;
export type ActionCodes = ObjectValues<typeof ACTION_CODES>;

// Make sure that there is no duplicate in values
export const SHORT_ACTION_CODES: Record<ActionCodes, string> = {
    [ACTION_CODES.ACTION_REGISTER_CHAMPIONSHIP]: "RC",
    [ACTION_CODES.ACTION_SEARCH_OPPONENT_CHAMPIONSHIP]: "SO",
    [ACTION_CODES.ACTION_SHOW_WEAPON_CATEGORY_SELECTION]: "WS",
    [ACTION_CODES.ACTION_SHOW_WEAPONS_SELECTION]: "WC",
    [ACTION_CODES.ACTION_UPDATE_WEAPONS_SELECTION]: "WU",
    [ACTION_CODES.ACTION_VALIDATE_WEAPONS_SELECTION]: "WV"
} as const;
type ShortActionCodes = ObjectValues<typeof SHORT_ACTION_CODES>;

export const MAPPING_ACTION_CODES_MODELS: Record<ShortActionCodes, DatabaseModels> = {
    [SHORT_ACTION_CODES.ACTION_REGISTER_CHAMPIONSHIP]: DATABASE_MODELS.ACTION_REGISTER_CHAMPIONSHIP,
    [SHORT_ACTION_CODES.ACTION_SEARCH_OPPONENT_CHAMPIONSHIP]: DATABASE_MODELS.ACTION_SEARCH_OPPONENT_CHAMPIONSHIP,
    [SHORT_ACTION_CODES.ACTION_SHOW_WEAPON_CATEGORY_SELECTION]: DATABASE_MODELS.ACTION_SHOW_WEAPON_CATEGORY_SELECTION,
    [SHORT_ACTION_CODES.ACTION_SHOW_WEAPONS_SELECTION]: DATABASE_MODELS.ACTION_SHOW_WEAPONS_SELECTION,
    [SHORT_ACTION_CODES.ACTION_UPDATE_WEAPONS_SELECTION]: DATABASE_MODELS.ACTION_UPDATE_WEAPONS_SELECTION,
    [SHORT_ACTION_CODES.ACTION_VALIDATE_WEAPONS_SELECTION]: DATABASE_MODELS.ACTION_VALIDATE_WEAPONS_SELECTION
};
