import type { ObjectValues } from "@bot-types";

export const DATABASE_MODELS = {
    ACTIONS: "ACTIONS",
    ACTION_REGISTER_CHAMPIONSHIP: "ACTION_REGISTER_CHAMPIONSHIP",
    ACTION_SEARCH_OPPONENT_CHAMPIONSHIP: "ACTION_SEARCH_OPPONENT_CHAMPIONSHIP",
    ACTION_SHOW_WEAPON_SELECTION_MENU: "ACTION_SHOW_WEAPON_SELECTION_MENU",
    ACTION_SHOW_WEAPON_CATEGORY_SELECTION: "ACTION_SHOW_WEAPON_CATEGORY_SELECTION",
    ACTION_SHOW_WEAPONS_SELECTION: "ACTION_SHOW_WEAPONS_SELECTION",
    ACTION_UPDATE_WEAPONS_SELECTION: "ACTION_UPDATE_WEAPONS_SELECTION",
    ACTION_VALIDATE_WEAPONS_SELECTION: "ACTION_VALIDATE_WEAPONS_SELECTION",

    PARTICIPANTS: "PARTICIPANTS",

    MATCH: "MATCH",
    MATCHMAKING_TICKET: "MATCHMAKING_TICKET"
} as const;

export type DatabaseModels = ObjectValues<typeof DATABASE_MODELS>;
