import type { ObjectValues } from "@bot-types";

export const DATABASE_MODELS = {
    ACTIONS: "ACTIONS",
    ACTION_REGISTER_CHAMPIONSHIP: "ACTION_REGISTER_CHAMPIONSHIP",
    ACTION_SEARCH_OPPONENT_CHAMPIONSHIP: "ACTION_SEARCH_OPPONENT_CHAMPIONSHIP",

    PARTICIPANTS: "PARTICIPANTS",

    MATCH: "MATCH",
    MATCHMAKING_TICKET: "MATCHMAKING_TICKET"
} as const;

export type DatabaseModels = ObjectValues<typeof DATABASE_MODELS>;
